# coding: utf-8

"""
    HR API

    Simple Example of an HR API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: steve1281@hotmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="HR API",
    author_email="steve1281@hotmail.com",
    url="",
    keywords=["Swagger", "HR API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Simple Example of an HR API  # noqa: E501
    """
)
