# coding: utf-8

"""
    HR API

    Simple Example of an HR API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: steve1281@hotmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_employees_get(self):
        """Test case for employees_get

        """
        pass

    def test_employees_id_get(self):
        """Test case for employees_id_get

        """
        pass

    def test_employees_post(self):
        """Test case for employees_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
