# coding: utf-8

"""
    HR API

    Simple Example of an HR API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: steve1281@hotmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.employees import Employees  # noqa: E501
from swagger_client.rest import ApiException


class TestEmployees(unittest.TestCase):
    """Employees unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmployees(self):
        """Test Employees"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.employees.Employees()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
