# coding: utf-8

# flake8: noqa
"""
    HR API

    Simple Example of an HR API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: steve1281@hotmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.employee import Employee
from swagger_client.models.employees import Employees
