apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec: 
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        env:
        - name: MESSAGE
          value: "Hello Kerbernetes!!"
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(MESSAGE); sleep 10; done"]
      restartPolicy: Never
