---
kind: Service
apiVersion: v1
metadata:
  name: taskservice
spec:
  selector:
    app: taskapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 5000
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30001
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskapp
  template:
    metadata:
      labels:
        app: taskapp
    spec:
      containers:
        - name: taskapp
          image: steve1281/flask-demo
          ports:
            - containerPort: 80
          volumeMounts:
            - name: dbase-storage
              mountPath: /usr/src/app/dbase
            - name: config-values
              mountPath: /usr/src/app/config
          env:
            - name: FLASK_DEBUG_MODE
              valueFrom:
                configMapKeyRef:
                  name: configvariable
                  key: FLASK_DEBUG_MODE
            - name: FLASK_HOST_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: configvariable
                  key: FLASK_HOST_IP_ADDRESS
            - name: FLASK_PORT_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: configvariable
                  key: FLASK_PORT_NUMBER
      volumes:
        - name: dbase-storage
          persistentVolumeClaim:
            claimName: dbase-pv-storage
        - name: config-values
          configMap:
            name: configvariable

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbase-pv-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configvariable
  namespace: default
data:
  FLASK_DEBUG_MODE : "True"
  FLASK_HOST_IP_ADDRESS : "0.0.0.0"
  FLASK_PORT_NUMBER : "80"
